// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoN-_LUgVYXDKR_wghX6nXloYtLBLYyqo',
    appId: '1:722695803890:web:41d2abba72a7f23a96916b',
    messagingSenderId: '722695803890',
    projectId: 'temphumid23',
    authDomain: 'temphumid23.firebaseapp.com',
    storageBucket: 'temphumid23.appspot.com',
    measurementId: 'G-9QB3FNGH5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKyUdBoIy1-shbGgnlCCJ5zamvO6UkUg',
    appId: '1:722695803890:android:f3441ba8cf5b569396916b',
    messagingSenderId: '722695803890',
    projectId: 'temphumid23',
    storageBucket: 'temphumid23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMYbAmaMgw3d9xj-z59h20ds6cc4aml8',
    appId: '1:722695803890:ios:651d1bd53594048096916b',
    messagingSenderId: '722695803890',
    projectId: 'temphumid23',
    storageBucket: 'temphumid23.appspot.com',
    iosBundleId: 'com.example.temphumidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWMYbAmaMgw3d9xj-z59h20ds6cc4aml8',
    appId: '1:722695803890:ios:c291be333578c95f96916b',
    messagingSenderId: '722695803890',
    projectId: 'temphumid23',
    storageBucket: 'temphumid23.appspot.com',
    iosBundleId: 'com.example.temphumidApp.RunnerTests',
  );
}
